### ISSUE TITLE
Auto login after registration

### ISSUE THREAD

**Issue by ghost** [nodemailer/wildduck-webmail#31]
Sorry, this is more of a question than an issue.

How is it possible to alter the POST /create route to automatically login the users after registration?

**Comment by andris9** [comment]
At this point you have both the username and password, so you could also perform an [authentication](https://docs.wildduck.email/api/#api-Authentication-PostAuth) and set up the authenticated session.

Currently not much effort is going into wildduck-webmail because there is a better implementation being built that eventually (once "ready enough") gets open sourced but so far hasn't.

<img width="1732" alt="Screenshot 2020-09-09 at 07 57 45" src="https://user-images.githubusercontent.com/132242/92556324-4f5e6000-f272-11ea-9b7b-bae4027d526a.png">

**Comment by laurivosandi** [comment]
Feel free to submit PR to improve the user experience, closing for now.

Note that saner option might be to handle user creation elsewhere and configure webmail to use SSO like we do it at k-space.ee 

https://git.k-space.ee/k-space/kube/src/branch/master/wildduck/webmail.yaml#L38
