### ISSUE TITLE
Templating & open registrations

### ISSUE THREAD

**Issue by Cannonb4ll** [nodemailer/wildduck-webmail#33]
Hi!

Just discovered this package via a friend, installed it and worked on the fly, awesome piece of software!

I just have 2 questions;

- Is it possible to apply your own custom template? It seems the current design is rather outdated.
- Are registrations always open? Is there a way to disable those and have a 'admin' only create these accounts?

Thanks!

**Comment by louis-lau** [comment]
Wildduck has no interface or open registration, so I assume you're talking about wildduck-webmail 😁. I've transferred the issue here.

Wildduck-webmails styling is just bootstrap. As far as I'm aware there's no option for overriding templates or styling. However, this is open source, and nodejs! You can just edit templates and the css in the source code.

User registration can be disabled in the config for wildduck-webmail: https://github.com/nodemailer/wildduck-webmail/blob/f356370fc0a63ed0d44c6852a121ba8f71d0ffc2/config/default.toml#L14

**Comment by Cannonb4ll** [comment]
Oh dear, I missed out on that one. I'm sorry, that was uncalled for from me.

That's just what I needed as an answer, thank you very much!
