### ISSUE TITLE
Config or option for base URL?

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [nodemailer/wildduck-webmail#5]
Hello, 

Is there any config or option for setting a base URL? Thanks.

**Comment by bunyevacz** [comment]
@UnKnoWn-Consortium: 
Wildduck-webmail will get all its call without base url, ie `<a href="/webmail/send?action=reply">`
All its `.css` and `.js` files are without dns prefix, it is always referenced from root (`/`).

So if you want on different url, then it is the job of the reverse proxy (nginx), no?

Please specify your exact usecase if I'm missing something. 

Otherwise, @andris9 I think this bugreport can be closed.

**Comment by laurivosandi** [comment]
No more details have been provided, closing for now
