### ISSUE TITLE
Multi-Domain Account Creation Error

### ISSUE THREAD

**Issue by ukwuezeobinna** [nodemailer/wildduck-webmail#52]
I set up WildDuck using the easy install script, and it works just fine.

I would want to add another domain and from the resources that I have seen, all I needed to do was add the domain in the “Allowed Domains” and restart the services.

Domain 2 shows on the Webmail, but I can't create any account. I get an error that says that “this username already exists”.

What am I doing wrong?

**Comment by louis-lau** [comment]
In wildduck users have a username and a main address. If you create john@example.com in the webmail, it will set the username to `john`. If you then try to create john@example2.com, it can't because the username `john` already exists. You should be able to create a user with another username via the api just fine (`john2` for example). It's just that the webmail account creation will use the local part of the address for the username.

**Comment by ukwuezeobinna** [comment]
I have limited dev experience. Is there a way to do this if I'm logged into the server via ssh? I will appreciate any help.

**Comment by laurivosandi** [comment]
You need to use Wildduck API to create user accounts manually in such case or automate it using the API

The API and relevant command is documented here: https://docs.wildduck.email/api/#operation/createUser

 You can for example use `curl` to invoke the API
